auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: LI, Yu from 1981
url: http://liyu1981.github.io
feed: /atom.xml
author_info: <a href="http://liyu1981.github.io/">LI,Yu</a>

myblog:
  gavatar: 33f01d4d7ce253886e83898c2111cfb1
  gpname: silkyk
  linkedin: https://www.linkedin.com/in/chen420
  github: http://www.github.com/silkyk?tab=repositories
  coverimgs: >
    'url("http://ialbum.ga/albums/Los%20Angeles/car-2617392_1280.jpg")',
    'url("http://ialbum.ga/albums/Los%20Angeles/echo-park-2766524_1280.jpg")',
    'url("http://ialbum.ga/albums/Los%20Angeles/car-2617392_1280.jpg")'
  postbgimg: http://ialbum.ga/albums/Los%20Angeles/beach-1630458_1280.jpg

prose:
  rooturl: "_posts"
  # siteurl: "http://liyu1981.github.io/"
  media: "images"
  metadata:
    _posts/blog:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          placeholder: "Input your title here"
          type: "text"

      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
          placeholder: "Input your abstract here"
          type: "text"

      - name: "layout"
        field:
          element: "hidden"
          value: "post"

      - name: "published"
        field:
          element: "hidden"
          value: "true"

      - name: "category"
        field:
          element: "hidden"
          value: "blog"
